export const iconRegistry: { brandMark: string; editors: Record<string, string>; shortcuts: Record<string, string> } = {
  brandMark: '9',
  editors: {
    Dashboard: '▦',
    'Product Grid': '▤',
    Cart: '▣',
    Transactions: '≡',
    'Returns & Refunds': '↺',
    'Shift & Cash Drawer': '₱',
    'Inventory Metrics': '◫',
    'Inventory Table': '▤',
    Purchasing: '↗',
    'Purchase Orders': '☰',
    'Waste Log': '⌁',
    'AI Insights': '✦',
    'WMA Forecast': '⌁',
    'Model Explanation': '∑',
    'Trend Analysis': '↗',
    'Basket Analysis': '⊕',
    'Customer Requests': '☷',
    Employees: '♙',
    Reports: '▥',
    'Settings Navigation': '⚙',
    'Business Settings': '⚙',
  },
  shortcuts: {
    'Point of Sale': '↗',
    Inventory: '▤',
    'AI Insights': '✦',
    Waste: '⌁',
    Reports: '▥',
    Settings: '⚙',
  },
}
